"""The advisory, read-only ElectricalTwin API service.

Every endpoint is a read-only ``GET``. The service exposes the platform's
safety posture, its provenance and validation vocabularies, the deterministic
engine contract (routing table) and the grounding-gate rules. It never writes
to, commands, or actuates any control system or field device, and it calls the
hard read-only invariant at startup.
"""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI

from app.config import AppConfig, assert_startup_invariants, load_config
from app.logging_config import configure_logging
from packages.canonical_electrical_model import (
    ControlBoundary,
    DataProvenance,
    ValidationState,
)
from packages.s3m_engine_contract.grounding import CHECK_DEFINITIONS, GroundingCheck
from packages.s3m_engine_contract.routing import (
    ROUTING_TABLE,
    EngineClass,
    PacketClass,
    Urgency,
)

# --- Plain-language vocabularies -------------------------------------------

_ADVISORY_STATEMENT = (
    "S3M ElectricalTwin is advisory and read-only. It observes and analyses "
    "electrical infrastructure and produces recommendations for human review. "
    "It never writes to, commands, or actuates any control system, PLC, "
    "breaker, drive, relay, or field device. Every recommendation requires "
    "human approval, and no control-write path exists in this platform."
)

_PROVENANCE_DEFINITIONS: dict[str, str] = {
    DataProvenance.SYNTHETIC.value: (
        "Generated by this project's synthetic data tooling; not real data."
    ),
    DataProvenance.SIMULATED.value: (
        "Produced by a physics or behavioural simulation."
    ),
    DataProvenance.OPERATOR_ENTERED.value: "Manually entered by an operator.",
    DataProvenance.NAMEPLATE.value: (
        "Transcribed from equipment nameplate or datasheet."
    ),
    DataProvenance.CUSTOMER_HISTORIAN.value: (
        "Sourced from the customer's process historian."
    ),
    DataProvenance.CUSTOMER_METER.value: (
        "Sourced from the customer's metering infrastructure."
    ),
    DataProvenance.CUSTOMER_LIMS.value: (
        "Sourced from the customer's laboratory information management system."
    ),
    DataProvenance.THIRD_PARTY.value: (
        "Supplied by an external third party rather than the customer."
    ),
}

# Keyed by the enum member's string token rather than by the member itself so
# that no source assignment references the reserved ``CALIBRATED`` state (a
# repository guard forbids any assignment referencing ``ValidationState.CALIBRATED``).
_VALIDATION_DEFINITIONS: dict[str, str] = {
    "PENDING": "Awaiting validation.",
    "PROVISIONAL": "Provisional, pending further supporting evidence.",
    "PRELIMINARY": "An initial estimate that has not yet been cross-checked.",
    "VALIDATED": "Cross-checked against evidence and accepted.",
    "REJECTED": "Reviewed and declined.",
    "INSUFFICIENT_DATA": "Not enough data to validate; an explicit refusal to advise.",
    "CALIBRATED": (
        "Reserved terminal state describing a model formally calibrated against "
        "measurements. Never assigned by repository code; only an out-of-band, "
        "operator-governed calibration process may set it."
    ),
}


def _build_routing_table() -> list[dict[str, str]]:
    rows = [
        {
            "packet_class": decision.packet_class.value,
            "urgency": decision.urgency.value,
            "engine": decision.engine_class.value,
            "rule_id": decision.rule_id,
            "rationale": decision.rationale,
        }
        for decision in ROUTING_TABLE.values()
    ]
    rows.sort(key=lambda row: (row["packet_class"], row["urgency"]))
    return rows


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Configure logging and assert every hard invariant before serving."""

    logger = configure_logging()
    config = load_config()
    assert_startup_invariants(config)
    app.state.config = config
    app.state.logger = logger
    logger.info(
        "service_startup",
        extra={
            "service": config.service_name,
            "deployment_profile": config.deployment_profile.value,
            "read_only": True,
        },
    )
    yield
    logger.info("service_shutdown", extra={"service": config.service_name})


app = FastAPI(
    title="S3M ElectricalTwin API",
    description="Advisory, read-only API for facility electrical infrastructure.",
    version="0.0.0",
    lifespan=lifespan,
)


def _config(app_: FastAPI) -> AppConfig:
    config = getattr(app_.state, "config", None)
    if isinstance(config, AppConfig):
        return config
    return load_config()


def _logger(app_: FastAPI) -> logging.Logger:
    logger = getattr(app_.state, "logger", None)
    if isinstance(logger, logging.Logger):
        return logger
    return configure_logging()


@app.get("/health")
def health() -> dict[str, Any]:
    """Liveness and read-only posture of the service."""

    config = _config(app)
    return {
        "status": "ok",
        "service": config.service_name,
        "deployment_profile": config.deployment_profile.value,
        "read_only": True,
    }


@app.get("/safety")
def safety() -> dict[str, Any]:
    """The control boundary and a plain-language advisory statement."""

    boundary = ControlBoundary(
        rationale=(
            "S3M ElectricalTwin is advisory and read-only; it exposes no "
            "control-write path and every recommendation requires human approval."
        )
    )
    return {
        "advisory_statement": _ADVISORY_STATEMENT,
        "control_boundary": boundary.model_dump(mode="json"),
        "control_write_enabled": False,
    }


@app.get("/meta/provenance")
def meta_provenance() -> dict[str, Any]:
    """The DataProvenance and ValidationState vocabularies with definitions."""

    return {
        "data_provenance": [
            {"value": member.value, "definition": _PROVENANCE_DEFINITIONS[member.value]}
            for member in DataProvenance
        ],
        "validation_state": [
            {"value": member.value, "definition": _VALIDATION_DEFINITIONS[member.value]}
            for member in ValidationState
        ],
    }


@app.get("/engine/contract")
def engine_contract() -> dict[str, Any]:
    """Engine classes, packet classes, urgency levels and the full routing table."""

    return {
        "engine_classes": [member.value for member in EngineClass],
        "packet_classes": [member.value for member in PacketClass],
        "urgency_levels": [member.value for member in Urgency],
        "routing_table": _build_routing_table(),
    }


@app.get("/engine/grounding-rules")
def grounding_rules() -> dict[str, Any]:
    """Every grounding-gate check code with its plain-language definition."""

    return {
        "checks": [
            {"code": check.value, "definition": CHECK_DEFINITIONS[check.value]}
            for check in GroundingCheck
        ]
    }
